# Generated by Django 4.2.7 on 2023-11-11 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Players',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('password', models.CharField(max_length=30)),
                ('record', models.IntegerField(default=0)),
                ('email', models.EmailField(default='', max_length=254)),
            ],
        ),
    ]
