# Generated by Django 4.2.7 on 2023-11-11 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_players_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='players',
            name='email',
        ),
    ]
