# Generated by Django 3.1.3 on 2020-12-01 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memory', '0002_auto_20201127_1900'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inputmodel',
            old_name='NickName',
            new_name='Name',
        ),
        migrations.AddField(
            model_name='inputmodel',
            name='Difficulty',
            field=models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], default='easy', max_length=20),
        ),
    ]
