# Generated by Django 3.1.3 on 2020-12-02 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memory', '0004_leaderboard'),
    ]

    operations = [
        migrations.RenameField(
            model_name='leaderboard',
            old_name='time_left',
            new_name='timeleft',
        ),
        migrations.RemoveField(
            model_name='leaderboard',
            name='Player_info',
        ),
        migrations.AddField(
            model_name='leaderboard',
            name='Difficulty',
            field=models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], default='easy', max_length=20),
        ),
        migrations.AddField(
            model_name='leaderboard',
            name='Name',
            field=models.CharField(default='blank', max_length=500),
            preserve_default=False,
        ),
    ]
