# Generated by Django 3.1.3 on 2020-12-02 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memory', '0005_auto_20201202_0202'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inputmodel',
            name='Name',
        ),
        migrations.AlterField(
            model_name='inputmodel',
            name='Difficulty',
            field=models.CharField(choices=[('Easy', 'Easy'), ('Medium', 'Medium'), ('Hard', 'Hard')], default='easy', max_length=20),
        ),
        migrations.AlterField(
            model_name='leaderboard',
            name='Difficulty',
            field=models.CharField(choices=[('Easy', 'Easy'), ('Medium', 'Medium'), ('Hard', 'Hard')], default='easy', max_length=20),
        ),
    ]
