# Generated by Django 4.2 on 2023-11-11 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memory', '0006_auto_20201202_1705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inputmodel',
            name='Difficulty',
            field=models.CharField(choices=[('Easy', 'Easy - (2x4)'), ('Medium', 'Medium - (3x4)'), ('Hard', 'Hard - (4x4)')], default='easy', max_length=20),
        ),
        migrations.AlterField(
            model_name='leaderboard',
            name='Difficulty',
            field=models.CharField(choices=[('Easy', 'Easy - (2x4)'), ('Medium', 'Medium - (3x4)'), ('Hard', 'Hard - (4x4)')], default='easy', max_length=20),
        ),
    ]
